### ISSUE TITLE
Utilização de Vuetify

### ISSUE THREAD

**Issue by lucassbarcelos** [mrocha98/trampoz-ui#1]
Mano vi as deps do teu projeto rodei o template aqui rsrs cara uma dica top, usa o plugin do Vuetify como galaria de componentes ele é top

**Comment by mrocha98** [comment]
Opa vlw pela dica manolo, na real eu mudei de lib, to usando o [PrimeVUE](https://www.primefaces.org/primevue/showcase/#/setup), vou subir as paradas em breve
